# @format

# docker-compose.yml

version: "3.8"

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - ./backend/:/code/app
    ports:
      - 8000:8000
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - 5173:5173
    expose:
      - 5173
    depends_on:
      - backend
  mongodb: 
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
